# Generated by Django 4.1 on 2023-04-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=250)),
                ('automatic_generated_ticket_number', models.CharField(default='', max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('notes', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
